Naming/VariableName:
  Enabled: false

# Offense count: 2
Lint/Loop:
  Exclude:
    - 'lib/azure/resource_management/ARM_interface.rb'

# Offense count: 14
Lint/UselessAssignment:
  Exclude:
    - 'lib/azure/resource_management/ARM_deployment_template.rb'
    - 'lib/azure/resource_management/ARM_interface.rb'
    - 'lib/azure/resource_management/windows_credentials.rb'
    - 'lib/chef/knife/azurerm_server_create.rb'
    - 'lib/chef/knife/azurerm_server_delete.rb'
    - 'lib/chef/knife/helpers/azurerm_base.rb'
    - 'spec/unit/azurerm_server_delete_spec.rb'
    - 'spec/unit/azurerm_server_show_spec.rb'

# Offense count: 1
Style/NumericPredicate:
  Exclude:
    - 'spec/**/*'
    - 'lib/chef/knife/helpers/azurerm_base.rb'
